resize_shape: [256, 256]
targets: ['Fire_Images']
model_file_paths: ["model/fire_cnn_classifier.h5"]
base_model_url: "https://github.com/tristann3/Fire-Detection-API-Project/releases/download/v.0.0.1"
model_sha256: "8747029386808b6bf2a85906fecb906cf891fb6f"
